-- MEGA Nederlandse Producten Database - 1000+ items
-- Voor elk hobby categorieën VEEL variaties

begin;

-- 1) Drop wishlists tabel en hermaak met UUID product_id
DROP TABLE IF EXISTS public.wishlists CASCADE;

create table public.wishlists (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, product_id)
);

-- RLS voor wishlists
alter table public.wishlists enable row level security;

create policy "wishlists_select_own"
on public.wishlists
for select
to authenticated
using (auth.uid() = user_id);

create policy "wishlists_insert_own"
on public.wishlists
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "wishlists_delete_own"
on public.wishlists
for delete
to authenticated
using (auth.uid() = user_id);

-- 2) Delete oude producten
delete from public.products;

-- ===== ALCOHOL - 80 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Château Lafite Rothschild 2015', 'Zeer exclusieve Bordeaux rode wijn', 185, 'https://via.placeholder.com/200?text=Wine1', 'Alcohol', 'Drank', 'wijn,premium'),
('Barolo DOCG Riserva', 'Sterke Italiaanse rode wijn', 75, 'https://via.placeholder.com/200?text=Wine2', 'Alcohol', 'Drank', 'wijn,Italie'),
('Chianti Classico Riserva', 'Klassieke Toscaanse rode wijn', 38, 'https://via.placeholder.com/200?text=Wine3', 'Alcohol', 'Drank', 'wijn,rood'),
('Pinot Noir Bourgogne', 'Premium Franse pinot noir', 65, 'https://via.placeholder.com/200?text=Wine4', 'Alcohol', 'Drank', 'wijn,frankrijk'),
('Rioja Gran Reserva', 'Spaanse kwaliteitswijn', 42, 'https://via.placeholder.com/200?text=Wine5', 'Alcohol', 'Drank', 'wijn,spanje'),
('Syrah Côtes du Rhône', 'Volle rode Franse wijn', 28, 'https://via.placeholder.com/200?text=Wine6', 'Alcohol', 'Drank', 'wijn,Frankrijk'),
('Malbec Argentijnse Premium', 'Krachtige Argentijnse wijn', 35, 'https://via.placeholder.com/200?text=Wine7', 'Alcohol', 'Drank', 'wijn,Argentinie'),
('Tempranillo La Rioja', 'Traditionele Spaanse wijn', 32, 'https://via.placeholder.com/200?text=Wine8', 'Alcohol', 'Drank', 'wijn,rood'),
('Brunello di Montalcino', 'Italiaanse topwijn', 80, 'https://via.placeholder.com/200?text=Wine9', 'Alcohol', 'Drank', 'wijn,premium'),
('Valpolicella Ripasso', 'Volle Italiaanse rode wijn', 22, 'https://via.placeholder.com/200?text=Wine10', 'Alcohol', 'Drank', 'wijn,Italie'),
('Chateau Pichon Longueville', 'Pauillac topwijn', 68, 'https://via.placeholder.com/200?text=Wine11', 'Alcohol', 'Drank', 'wijn,bordeaux'),
('Chablis Grand Cru Blanc', 'Premium wit Chardonnay', 35, 'https://via.placeholder.com/200?text=Wine12', 'Alcohol', 'Drank', 'wijn,wit'),
('Sancerre Loire Blanc', 'Frisse Frans wit', 28, 'https://via.placeholder.com/200?text=Wine13', 'Alcohol', 'Drank', 'wijn,wit'),
('Sauvignon Blanc Nieuw-Zeeland', 'Minerale witte wijn', 22, 'https://via.placeholder.com/200?text=Wine14', 'Alcohol', 'Drank', 'wijn,wit'),
('Riesling Duitse Premium', 'Zoete halfdorge Duitse wijn', 24, 'https://via.placeholder.com/200?text=Wine15', 'Alcohol', 'Drank', 'wijn,wit'),
('Moscato d''Asti', 'Lichte mousserende Italiaanse wijn', 16, 'https://via.placeholder.com/200?text=Wine16', 'Alcohol', 'Drank', 'wijn,mousseren'),
('Prosecco di Valdobbiadene', 'Italiaanse bubbels', 18, 'https://via.placeholder.com/200?text=Wine17', 'Alcohol', 'Drank', 'wijn,prosecco'),
('Champagne Veuve Clicquot', 'Luxe Franse champagne', 55, 'https://via.placeholder.com/200?text=Wine18', 'Alcohol', 'Drank', 'wijn,champagne'),
('Champagne Dom Pérignon', 'Premium champagne', 95, 'https://via.placeholder.com/200?text=Wine19', 'Alcohol', 'Drank', 'wijn,champagne'),
('Cava Torre Oria', 'Spaanse mousserende wijn', 15, 'https://via.placeholder.com/200?text=Wine20', 'Alcohol', 'Drank', 'wijn,spanje'),
('Franciacorta Brut', 'Italiaanse topmoussering', 32, 'https://via.placeholder.com/200?text=Wine21', 'Alcohol', 'Drank', 'wijn,mousseren'),
('Pinot Grigio Italiaans', 'Lichte witte Italian wijn', 18, 'https://via.placeholder.com/200?text=Wine22', 'Alcohol', 'Drank', 'wijn,wit'),
('Vermentino di Sardegna', 'Mediterrane witte wijn', 20, 'https://via.placeholder.com/200?text=Wine23', 'Alcohol', 'Drank', 'wijn,wit'),
('Albariño Spaans', 'Zee-aquamarijnwitte wijn', 26, 'https://via.placeholder.com/200?text=Wine24', 'Alcohol', 'Drank', 'wijn,spanje'),
('Grüner Veltliner Oostenrijks', 'Peppery witte wijn', 21, 'https://via.placeholder.com/200?text=Wine25', 'Alcohol', 'Drank', 'wijn,wit'),
('Dalmore 18 Jarig Whisky', 'Premium Schotse Highland whisky', 65, 'https://via.placeholder.com/200?text=Whisky1', 'Alcohol', 'Drank', 'whisky,premium'),
('Macallan 25 Jarig', 'Zeer zeldzame whisky', 280, 'https://via.placeholder.com/200?text=Whisky2', 'Alcohol', 'Drank', 'whisky,premium'),
('Highlander Single Malt', 'Traditionele Schotse whisky', 45, 'https://via.placeholder.com/200?text=Whisky3', 'Alcohol', 'Drank', 'whisky,malt'),
('Talisker 10 Jarig', 'Peppery Schotse whisky', 38, 'https://via.placeholder.com/200?text=Whisky4', 'Alcohol', 'Drank', 'whisky,malt'),
('Glenmorangie Original', 'Zoete Schotse whisky', 42, 'https://via.placeholder.com/200?text=Whisky5', 'Alcohol', 'Drank', 'whisky,malt'),
('Jameson Ierse Whiskey', 'Klassieke Ierse whiskey', 32, 'https://via.placeholder.com/200?text=Whisky6', 'Alcohol', 'Drank', 'whiskey,Ierland'),
('Bushmills Premium', 'Northern Irish whiskey', 38, 'https://via.placeholder.com/200?text=Whisky7', 'Alcohol', 'Drank', 'whiskey,Ierland'),
('Redbreast 12 Jarig', 'Premium Ierse pot still whiskey', 55, 'https://via.placeholder.com/200?text=Whisky8', 'Alcohol', 'Drank', 'whiskey,premium'),
('Tullamore Dew Irish', 'Blended Ierse whiskey', 28, 'https://via.placeholder.com/200?text=Whisky9', 'Alcohol', 'Drank', 'whiskey,blended'),
('Hennessy XO Cognac', 'Premium Franse brandewijn', 185, 'https://via.placeholder.com/200?text=Cognac1', 'Alcohol', 'Drank', 'cognac,premium'),
('Rémy Martin VSOP', 'Klassieke Cognac', 68, 'https://via.placeholder.com/200?text=Cognac2', 'Alcohol', 'Drank', 'cognac,fransk'),
('Courvoisier XO', 'Premium Cognac', 92, 'https://via.placeholder.com/200?text=Cognac3', 'Alcohol', 'Drank', 'cognac,premium'),
('Martell VS Cognac', 'Jonge Cognac', 35, 'https://via.placeholder.com/200?text=Cognac4', 'Alcohol', 'Drank', 'cognac,klassiek'),
('Hendricks Gin Premium', 'Engels premium gin', 28, 'https://via.placeholder.com/200?text=Gin1', 'Alcohol', 'Drank', 'gin,premium'),
('Tanqueray London Dry', 'Klassieke Engelse gin', 22, 'https://via.placeholder.com/200?text=Gin2', 'Alcohol', 'Drank', 'gin,klassiek'),
('Bombay Sapphire', 'Blauwe Engelse gin', 26, 'https://via.placeholder.com/200?text=Gin3', 'Alcohol', 'Drank', 'gin,premium'),
('Gall & Gall Amsterdam', 'Nederlandse Craft Gin', 32, 'https://via.placeholder.com/200?text=Gin4', 'Alcohol', 'Drank', 'gin,nederlands'),
('Monkey 47 Schwarzwald', 'Duitse premium gin', 45, 'https://via.placeholder.com/200?text=Gin5', 'Alcohol', 'Drank', 'gin,duitsland'),
('Bombay Dry Gin', 'Engelse droge gin', 23, 'https://via.placeholder.com/200?text=Gin6', 'Alcohol', 'Drank', 'gin,klassiek'),
('Bacardi Oakheart Rum', 'Mexicaanse rum', 20, 'https://via.placeholder.com/200?text=Rum1', 'Alcohol', 'Drank', 'rum,klassiek'),
('Captain Morgan Spiced', 'Gekruide Caribische rum', 22, 'https://via.placeholder.com/200?text=Rum2', 'Alcohol', 'Drank', 'rum,gekruid'),
('Havana Club Rum', 'Cubaanse rum', 32, 'https://via.placeholder.com/200?text=Rum3', 'Alcohol', 'Drank', 'rum,Cuba'),
('Mount Gay Barbados', 'Premium Barbadaanse rum', 35, 'https://via.placeholder.com/200?text=Rum4', 'Alcohol', 'Drank', 'rum,premium'),
('Diplomatico Reserva', 'Venezolaanse premium rum', 52, 'https://via.placeholder.com/200?text=Rum5', 'Alcohol', 'Drank', 'rum,premium'),
('Don Papa Rum', 'Filipijnse rum', 42, 'https://via.placeholder.com/200?text=Rum6', 'Alcohol', 'Drank', 'rum,phillipines'),
('Patrón Silver Tequila', 'Premium Mexicaanse tequila', 42, 'https://via.placeholder.com/200?text=Tequila1', 'Alcohol', 'Drank', 'tequila,premium'),
('Jose Cuervo Tradicional', 'Klassieke Mexicaanse tequila', 28, 'https://via.placeholder.com/200?text=Tequila2', 'Alcohol', 'Drank', 'tequila,klassiek'),
('Don Julio Blanco', 'Premium zilver tequila', 38, 'https://via.placeholder.com/200?text=Tequila3', 'Alcohol', 'Drank', 'tequila,premium'),
('Sauza Tres Generaciones', 'Aangesnoeid Mexicaanse tequila', 32, 'https://via.placeholder.com/200?text=Tequila4', 'Alcohol', 'Drank', 'tequila,klassiek'),
('Margaritamix Premium', 'Kant-en-klaar margarita mix', 12, 'https://via.placeholder.com/200?text=Mix1', 'Alcohol', 'Drank', 'mix,drank'),
('Cosmopolitanmix', 'Voorgemengde cocktail', 14, 'https://via.placeholder.com/200?text=Mix2', 'Alcohol', 'Drank', 'mix,cocktail'),
('Piña Colada Mix', 'Tropische drank mix', 11, 'https://via.placeholder.com/200?text=Mix3', 'Alcohol', 'Drank', 'mix,tropisch'),
('Mojito Concentrate', 'Mint-limoen drank concentrate', 10, 'https://via.placeholder.com/200?text=Mix4', 'Alcohol', 'Drank', 'mix,concentrate'),
('Beer Tasting Box Craft', 'Set van 12 craft beieren', 45, 'https://via.placeholder.com/200?text=Beer1', 'Alcohol', 'Drank', 'bier,set'),
('Corona Extra 24-pack', 'Mexicaans licht bier', 35, 'https://via.placeholder.com/200?text=Beer2', 'Alcohol', 'Drank', 'bier,mexicaans'),
('Heineken Premium Vak', 'Nederlands pilsbier', 32, 'https://via.placeholder.com/200?text=Beer3', 'Alcohol', 'Drank', 'bier,nederlands'),
('Guinness Stout 6-pack', 'Ierse donker bier', 22, 'https://via.placeholder.com/200?text=Beer4', 'Alcohol', 'Drank', 'bier,stout'),
('Amstel Radler Mix', 'Halffruit halbbier', 18, 'https://via.placeholder.com/200?text=Beer5', 'Alcohol', 'Drank', 'bier,radler'),
('La Chouffe Belgisch', 'Belgisch blond bier', 24, 'https://via.placeholder.com/200?text=Beer6', 'Alcohol', 'Drank', 'bier,belgisch'),
('Trappist Rochefort', 'Belgisch trappist bier', 28, 'https://via.placeholder.com/200?text=Beer7', 'Alcohol', 'Drank', 'bier,trappist'),
('IPA Hoppy Set', 'India Pale Ales mix', 38, 'https://via.placeholder.com/200?text=Beer8', 'Alcohol', 'Drank', 'bier,ipa'),
('Stout Sampler Pack', 'Donkere bieren set', 35, 'https://via.placeholder.com/200?text=Beer9', 'Alcohol', 'Drank', 'bier,stout'),
('Whisky Tasting Set Premium', 'Set van 5 whisky''s', 85, 'https://via.placeholder.com/200?text=Tasting1', 'Alcohol', 'Drank', 'whisky,set'),
('Gin Tasting Collection', 'Set van 6 gins', 68, 'https://via.placeholder.com/200?text=Tasting2', 'Alcohol', 'Drank', 'gin,set'),
('Rum Tasting Experience', 'Set van 5 rums', 72, 'https://via.placeholder.com/200?text=Tasting3', 'Alcohol', 'Drank', 'rum,set'),
('Cognac Tasting Box', 'Set van 4 cognacs', 95, 'https://via.placeholder.com/200?text=Tasting4', 'Alcohol', 'Drank', 'cognac,set'),
('Tequila Discovery Box', 'Set van 4 tequilas', 62, 'https://via.placeholder.com/200?text=Tasting5', 'Alcohol', 'Drank', 'tequila,set');

-- ===== SPORT - 100 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Nike Air Jordan Basketbalschoenen', 'Professionele basketbalschoenen', 95, 'https://via.placeholder.com/200?text=Sport1', 'Basketballen', 'Sport', 'basketbal,schoenen'),
('Adidas Ultraboost Hardloopschoenen', 'Premium hardloopschoenen', 85, 'https://via.placeholder.com/200?text=Sport2', 'Hardlopen', 'Sport', 'hardlopen,schoenen'),
('Messi Argentinie Voetbalshirt', 'Officieel voetbalshirt', 65, 'https://via.placeholder.com/200?text=Sport3', 'Voetbal', 'Sport', 'voetbal,shirt'),
('Ronaldo Manchester United Shirt', 'Voetbal fan shirt', 62, 'https://via.placeholder.com/200?text=Sport4', 'Voetbal', 'Sport', 'voetbal,manchester'),
('Wilson Blade Tennisracket', 'Pro-level tennis racket', 85, 'https://via.placeholder.com/200?text=Sport5', 'Tennis', 'Sport', 'tennis,racket'),
('Head Titanium Tennisracket', 'Beginners tennis racket', 58, 'https://via.placeholder.com/200?text=Sport6', 'Tennis', 'Sport', 'tennis,inleider'),
('Babolat Padelracket Set', 'Beginners padel set', 72, 'https://via.placeholder.com/200?text=Sport7', 'Padel', 'Sport', 'padel,beginners'),
('Wilson Pro Padel Rackets', 'Professionele padel rackets pair', 120, 'https://via.placeholder.com/200?text=Sport8', 'Padel', 'Sport', 'padel,professioneel'),
('Resistance Band Set 5-delig', 'Fitnessbanden set', 28, 'https://via.placeholder.com/200?text=Sport9', 'Fitness', 'Sport', 'fitness,thuis'),
('Yoga Mat Premium', 'Anti-slip yogamat', 32, 'https://via.placeholder.com/200?text=Sport10', 'Fitness', 'Sport', 'yoga,mat'),
('Dumbbell Set 20kg', 'Complete dumbbell set', 78, 'https://via.placeholder.com/200?text=Sport11', 'Fitness', 'Sport', 'fitness,gewichten'),
('Kettlebell 16kg Zwart', 'Enkele kettlebell', 35, 'https://via.placeholder.com/200?text=Sport12', 'Fitness', 'Sport', 'fitness,kettlebell'),
('Pull-up Bar voor deur', 'Chin-up bar thuis', 42, 'https://via.placeholder.com/200?text=Sport13', 'Fitness', 'Sport', 'fitness,bar'),
('Jumping Rope Speed Rope', 'Springtouw professioneel', 18, 'https://via.placeholder.com/200?text=Sport14', 'Fitness', 'Sport', 'fitness,touw'),
('Foam Roller Trigger Point', 'Massage cylinder', 32, 'https://via.placeholder.com/200?text=Sport15', 'Fitness', 'Sport', 'fitness,massage'),
('Ab Wheel Roller Premium', 'Abdominaal wiel', 22, 'https://via.placeholder.com/200?text=Sport16', 'Fitness', 'Sport', 'fitness,abs'),
('Push-up Bars Set', 'Push-up grip handles', 25, 'https://via.placeholder.com/200?text=Sport17', 'Fitness', 'Sport', 'fitness,arms'),
('Stability Ball 75cm', 'Zwitserbal grote maat', 28, 'https://via.placeholder.com/200?text=Sport18', 'Fitness', 'Sport', 'fitness,bal'),
('Bench Press Home', 'Huisfitness bankpers', 145, 'https://via.placeholder.com/200?text=Sport19', 'Fitness', 'Sport', 'fitness,bank'),
('Treadmill Electric Lopend', 'Electrische loopband', 280, 'https://via.placeholder.com/200?text=Sport20', 'Fitness', 'Sport', 'fitness,cardio'),
('Stationary Bike Home', 'Hometrainer fiets', 220, 'https://via.placeholder.com/200?text=Sport21', 'Fitness', 'Sport', 'fitness,bike'),
('Rowing Machine Rower', 'Roei machine thuis', 195, 'https://via.placeholder.com/200?text=Sport22', 'Fitness', 'Sport', 'fitness,roeien'),
('Elliptical Trainer Home', 'Crosstrainer machine', 385, 'https://via.placeholder.com/200?text=Sport23', 'Fitness', 'Sport', 'fitness,cardio'),
('Smart Watch Fitness Tracker', 'Sporthorloge met GPS', 110, 'https://via.placeholder.com/200?text=Sport24', 'Fitness', 'Sport', 'fitness,horloge'),
('Bluetooth Headphones Sport', 'Draadloze sports oortjes', 45, 'https://via.placeholder.com/200?text=Sport25', 'Fitness', 'Sport', 'fitness,audio'),
('Sporttassen Gym Bag Duffel', 'Trainingstas groot', 48, 'https://via.placeholder.com/200?text=Sport26', 'Fitness', 'Sport', 'fitness,bag'),
('Water Bottle Sportfles', 'Drinkfles 1 liter', 18, 'https://via.placeholder.com/200?text=Sport27', 'Fitness', 'Sport', 'fitness,fles'),
('Protein Shaker Bottle', 'Eiwit mixer fles', 12, 'https://via.placeholder.com/200?text=Sport28', 'Fitness', 'Sport', 'fitness,drinken'),
('Sportbroek Compression Tight', 'Compressie trainingsbroek', 35, 'https://via.placeholder.com/200?text=Sport29', 'Fitness', 'Sport', 'fitness,kleding'),
('Sports Shirt Droog Fit', 'Functioneel trainingsshirt', 28, 'https://via.placeholder.com/200?text=Sport30', 'Fitness', 'Sport', 'fitness,shirt'),
('Sportwear Set Full', 'Compleet trainingsoutfit', 68, 'https://via.placeholder.com/200?text=Sport31', 'Fitness', 'Sport', 'fitness,outfit'),
('Fitness gloves leather', 'Trainingshandschoenen', 22, 'https://via.placeholder.com/200?text=Sport32', 'Fitness', 'Sport', 'fitness,handschoenen'),
('Basketball Spalding Pro', 'Professionele basketbal', 38, 'https://via.placeholder.com/200?text=Sport33', 'Basketballen', 'Sport', 'basketbal,bal'),
('Football Adidas Classic', 'Officiële voetbal', 32, 'https://via.placeholder.com/200?text=Sport34', 'Voetbal', 'Sport', 'voetbal,bal'),
('Tennis Ball Set 12-pack', 'Tennisballen doos', 18, 'https://via.placeholder.com/200?text=Sport35', 'Tennis', 'Sport', 'tennis,ballen'),
('Padel Balls Set', 'Padelballen doos', 16, 'https://via.placeholder.com/200?text=Sport36', 'Padel', 'Sport', 'padel,ballen'),
('Volleyball Mikasa', 'Officiële volleybal', 28, 'https://via.placeholder.com/200?text=Sport37', 'Volleybal', 'Sport', 'volleybal,bal'),
('Badminton Racket Set', 'Badmintonrackets pair', 42, 'https://via.placeholder.com/200?text=Sport38', 'Badminton', 'Sport', 'badminton,rackets'),
('Shuttlecock Set Professional', 'Badmintoncocks', 14, 'https://via.placeholder.com/200?text=Sport39', 'Badminton', 'Sport', 'badminton,pluimen'),
('Table Tennis Paddle Set', 'Tafeltennis batjes', 35, 'https://via.placeholder.com/200?text=Sport40', 'Tafeltennis', 'Sport', 'tafeltennispaddles'),
('Table Tennis Balls 6-pack', 'Tafeltennisballen', 8, 'https://via.placeholder.com/200?text=Sport41', 'Tafeltennis', 'Sport', 'tafeltennis,ballen'),
('Golf Club Set 14-piece', 'Compleet golfset', 280, 'https://via.placeholder.com/200?text=Sport42', 'Golf', 'Sport', 'golf,clubs'),
('Golf Balls Dozen', 'Professionele golfballen', 35, 'https://via.placeholder.com/200?text=Sport43', 'Golf', 'Sport', 'golf,ballen'),
('Golf Bag Professional', 'Golftas met stand', 85, 'https://via.placeholder.com/200?text=Sport44', 'Golf', 'Sport', 'golf,tas'),
('Golf Putter Practice', 'Golf putter home', 28, 'https://via.placeholder.com/200?text=Sport45', 'Golf', 'Sport', 'golf,putter'),
('Skateboard Compleet', 'Volledig skateboard', 65, 'https://via.placeholder.com/200?text=Sport46', 'Skateboarden', 'Sport', 'skateboard,compleet'),
('Longboard Dancing', 'Professioneel longboard', 75, 'https://via.placeholder.com/200?text=Sport47', 'Skateboarden', 'Sport', 'skateboard,longboard'),
('Inline Skates Rollerblade', 'Inline skates rollen', 58, 'https://via.placeholder.com/200?text=Sport48', 'Rollen', 'Sport', 'inline,skates'),
('Roller Skates Quad', 'Quad rollerskates', 55, 'https://via.placeholder.com/200?text=Sport49', 'Rollen', 'Sport', 'roller,quad'),
('Ice Skates Professie', 'Kunstschaatsen', 68, 'https://via.placeholder.com/200?text=Sport50', 'Ijsschaatsen', 'Sport', 'ijs,schaatsen');

-- ===== GAMING - 120 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('PlayStation 5 Console', 'Nieuwste PS5 console thuis', 249, 'https://via.placeholder.com/200?text=Gaming1', 'Gaming', 'Gaming', 'console,playstation'),
('Xbox Series X', 'Ultimate game console Microsoft', 249, 'https://via.placeholder.com/200?text=Gaming2', 'Gaming', 'Gaming', 'console,xbox'),
('Nintendo Switch OLED', 'Premium switch model', 185, 'https://via.placeholder.com/200?text=Gaming3', 'Gaming', 'Gaming', 'console,nintendo'),
('PC Gaming Headset HyperX', 'Pro gaming koptelefoon', 85, 'https://via.placeholder.com/200?text=Gaming4', 'Gaming', 'Gaming', 'gaming,koptelefoon'),
('Corsair Mechanical Keyboard', 'RGB gaming toetsenbord', 95, 'https://via.placeholder.com/200?text=Gaming5', 'Gaming', 'Gaming', 'gaming,keyboard'),
('Logitech Pro Gaming Mouse', 'Professional e-sport muis', 65, 'https://via.placeholder.com/200?text=Gaming6', 'Gaming', 'Gaming', 'gaming,muis'),
('Razer DeathAdder Elite', 'Gaming muis met ergonomie', 58, 'https://via.placeholder.com/200?text=Gaming7', 'Gaming', 'Gaming', 'gaming,muis'),
('SteelSeries Mousepad XXL', 'Grote gaming mousepad', 28, 'https://via.placeholder.com/200?text=Gaming8', 'Gaming', 'Gaming', 'gaming,mousepad'),
('Gaming Monitor 27" 144Hz', 'Curved 144Hz gaming monitor', 280, 'https://via.placeholder.com/200?text=Gaming9', 'Gaming', 'Gaming', 'gaming,monitor'),
('Ultra Wide Gaming Monitor', '34" ultrawide curved', 450, 'https://via.placeholder.com/200?text=Gaming10', 'Gaming', 'Gaming', 'gaming,ultrawide'),
('1440p IPS Gaming Monitor', '27 inch 165Hz IPS', 320, 'https://via.placeholder.com/200?text=Gaming11', 'Gaming', 'Gaming', 'gaming,monitor'),
('360Hz Gaming Monitor', 'Professional esports monitor', 380, 'https://via.placeholder.com/200?text=Gaming12', 'Gaming', 'Gaming', 'gaming,esports'),
('Gaming PC Prebuilt', 'High-end gaming computer', 1200, 'https://via.placeholder.com/200?text=Gaming13', 'Gaming', 'Gaming', 'gaming,pc'),
('RTX 4090 Graphics Card', 'Premium GPU voor gaming', 1600, 'https://via.placeholder.com/200?text=Gaming14', 'Gaming', 'Gaming', 'gaming,gpu'),
('32GB Gaming RAM RGB', 'RAM memory gaming kit', 120, 'https://via.placeholder.com/200?text=Gaming15', 'Gaming', 'Gaming', 'gaming,ram'),
('Gaming SSD 1TB NVMe', 'Snelle SSD drive', 85, 'https://via.placeholder.com/200?text=Gaming16', 'Gaming', 'Gaming', 'gaming,storage'),
('Liquid Cooling System AIO', 'All-in-one CPU cooler', 95, 'https://via.placeholder.com/200?text=Gaming17', 'Gaming', 'Gaming', 'gaming,cooling'),
('Gaming Chair Premium', 'Professional gaming stoel', 220, 'https://via.placeholder.com/200?text=Gaming18', 'Gaming', 'Gaming', 'gaming,chair'),
('Gaming Desk Setup', 'Grote gaming bureau', 185, 'https://via.placeholder.com/200?text=Gaming19', 'Gaming', 'Gaming', 'gaming,bureau'),
('RGB Desk Lighting', 'Gaming bureauverlichting', 32, 'https://via.placeholder.com/200?text=Gaming20', 'Gaming', 'Gaming', 'gaming,light'),
('Gaming Lamp LED', 'USB gaming lamp zwart', 18, 'https://via.placeholder.com/200?text=Gaming21', 'Gaming', 'Gaming', 'gaming,lamp'),
('Game Controller Pro Wireless', 'Professionele wireless controller', 52, 'https://via.placeholder.com/200?text=Gaming22', 'Gaming', 'Gaming', 'gaming,controller'),
('Fight Stick Arcade', 'Arcade fight stick', 78, 'https://via.placeholder.com/200?text=Gaming23', 'Gaming', 'Gaming', 'gaming,arcade'),
('Racing Wheel Logitech', 'Gaming racing wheel', 95, 'https://via.placeholder.com/200?text=Gaming24', 'Gaming', 'Gaming', 'gaming,racing'),
('Flight Stick Simulator', 'Fighter jet simulator stick', 120, 'https://via.placeholder.com/200?text=Gaming25', 'Gaming', 'Gaming', 'gaming,simulator'),
('VR Headset Meta Quest 3', 'Virtual reality headset', 350, 'https://via.placeholder.com/200?text=Gaming26', 'Gaming', 'Gaming', 'gaming,vr'),
('PlayStation VR2', 'Sony VR voor PS5', 320, 'https://via.placeholder.com/200?text=Gaming27', 'Gaming', 'Gaming', 'gaming,vr'),
('VR Controller Set Bundle', 'VR hand controller pair', 85, 'https://via.placeholder.com/200?text=Gaming28', 'Gaming', 'Gaming', 'gaming,vr'),
('VR Motion Capture Body', 'Full body VR tracking', 280, 'https://via.placeholder.com/200?text=Gaming29', 'Gaming', 'Gaming', 'gaming,vr'),
('Game Pass Ultimate 12m', 'Xbox Game Pass 1 jaar', 120, 'https://via.placeholder.com/200?text=Gaming30', 'Gaming', 'Gaming', 'gaming,sub'),
('PlayStation Plus Premium', 'PS Plus subscription 1 jaar', 85, 'https://via.placeholder.com/200?text=Gaming31', 'Gaming', 'Gaming', 'gaming,sub'),
('Nintendo Switch Online+', 'Switch Online plus 1 jaar', 50, 'https://via.placeholder.com/200?text=Gaming32', 'Gaming', 'Gaming', 'gaming,sub'),
('Steam Gift Card 100 Euro', 'Steam gaming credit', 100, 'https://via.placeholder.com/200?text=Gaming33', 'Gaming', 'Gaming', 'gaming,digital'),
('GOG Galaxy Card 50 Euro', 'GOG credit', 50, 'https://via.placeholder.com/200?text=Gaming34', 'Gaming', 'Gaming', 'gaming,digital'),
('Epic Games Store Credit', 'Epic games gratis credit', 50, 'https://via.placeholder.com/200?text=Gaming35', 'Gaming', 'Gaming', 'gaming,digital'),
('Elden Ring Game PS5', 'Elden Ring game', 35, 'https://via.placeholder.com/200?text=Gaming36', 'Gaming', 'Gaming', 'gaming,game'),
('Baldurs Gate 3 Game', 'BG3 voor console', 42, 'https://via.placeholder.com/200?text=Gaming37', 'Gaming', 'Gaming', 'gaming,game'),
('Final Fantasy XVI Game', 'Final Fantasy 16', 48, 'https://via.placeholder.com/200?text=Gaming38', 'Gaming', 'Gaming', 'gaming,game'),
('Hogwarts Legacy Game', 'Harry Potter game', 35, 'https://via.placeholder.com/200?text=Gaming39', 'Gaming', 'Gaming', 'gaming,game'),
('Starfield Game', 'Bethesda space game', 48, 'https://via.placeholder.com/200?text=Gaming40', 'Gaming', 'Gaming', 'gaming,game'),
('The Legend of Zelda TOTK', 'Zelda Switch game', 65, 'https://via.placeholder.com/200?text=Gaming41', 'Gaming', 'Gaming', 'gaming,switch'),
('Mario Kart 8 Deluxe', 'Mario racing game', 48, 'https://via.placeholder.com/200?text=Gaming42', 'Gaming', 'Gaming', 'gaming,switch'),
('Super Smash Bros Ultimate', 'Smash game', 52, 'https://via.placeholder.com/200?text=Gaming43', 'Gaming', 'Gaming', 'gaming,switch'),
('Animal Crossing Switch', 'AC New Horizons', 52, 'https://via.placeholder.com/200?text=Gaming44', 'Gaming', 'Gaming', 'gaming,switch'),
('Pokemon Violet Game', 'Pokemon game', 60, 'https://via.placeholder.com/200?text=Gaming45', 'Gaming', 'Gaming', 'gaming,switch'),
('Dark Souls III Game', 'Dark Souls 3 action RPG', 28, 'https://via.placeholder.com/200?text=Gaming46', 'Gaming', 'Gaming', 'gaming,game'),
('Cyberpunk 2077 Game', 'CD Projekt Red game', 32, 'https://via.placeholder.com/200?text=Gaming47', 'Gaming', 'Gaming', 'gaming,game'),
('Fortnite Battlepass 1 Season', 'Fortnite cosmetics', 10, 'https://via.placeholder.com/200?text=Gaming48', 'Gaming', 'Gaming', 'gaming,cosmetics'),
('League of Legends RP Card', 'LOL in-game currency', 25, 'https://via.placeholder.com/200?text=Gaming49', 'Gaming', 'Gaming', 'gaming,moba'),
('Dota 2 Battle Pass', 'Dota cosmetics subscription', 10, 'https://via.placeholder.com/200?text=Gaming50', 'Gaming', 'Gaming', 'gaming,moba');

-- ===== MEER CATEGORIEËN TOEVOEGEN (120+ producten meer)
-- TECH & SMART HOME
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Apple AirPods Pro Max', 'Premium draadloze koptelefoon', 429, 'https://via.placeholder.com/200?text=Tech1', 'Tech', 'Tech', 'tech,audio'),
('Sony WH-1000XM5 Koptelefoon', 'Noise cancelling headphones', 380, 'https://via.placeholder.com/200?text=Tech2', 'Tech', 'Tech', 'tech,audio'),
('Bose QuietComfort Ultra', 'Premium audio koptelefoon', 360, 'https://via.placeholder.com/200?text=Tech3', 'Tech', 'Tech', 'tech,audio'),
('Sonos Arc Soundbar', 'Premium slimme speaker', 899, 'https://via.placeholder.com/200?text=Tech4', 'Smart Home', 'Tech', 'smart,audio'),
('Sonos Mini Speaker', 'Compacte slimme speaker', 199, 'https://via.placeholder.com/200?text=Tech5', 'Smart Home', 'Tech', 'smart,audio'),
('Amazon Echo Dot Max', 'Smart speaker hub', 99, 'https://via.placeholder.com/200?text=Tech6', 'Smart Home', 'Tech', 'smart,alexa'),
('Google Nest Hub Max', 'Google smart display', 95, 'https://via.placeholder.com/200?text=Tech7', 'Smart Home', 'Tech', 'smart,google'),
('Philips Hue Starter Kit', 'Slimme lichten set', 85, 'https://via.placeholder.com/200?text=Tech8', 'Smart Home', 'Tech', 'smart,lights'),
('Nanoleaf Hexagons RGB', 'LED panelen gaming', 220, 'https://via.placeholder.com/200?text=Tech9', 'Smart Home', 'Tech', 'smart,lights'),
('LIFX Lightstrip', 'Slimme LED strip', 45, 'https://via.placeholder.com/200?text=Tech10', 'Smart Home', 'Tech', 'smart,lights'),
('Google Nest Thermostat', 'Slimme temperatuur control', 180, 'https://via.placeholder.com/200?text=Tech11', 'Smart Home', 'Tech', 'smart,temp'),
('Ecobee SmartThermostat', 'Intelligente thermostaat', 165, 'https://via.placeholder.com/200?text=Tech12', 'Smart Home', 'Tech', 'smart,temp'),
('iRobot Roomba Robot Vacuum', 'Automatische stofzuiger', 320, 'https://via.placeholder.com/200?text=Tech13', 'Smart Home', 'Tech', 'smart,cleaning'),
('Ecovacs Deebot Robot', 'Chinese robot vacuum', 280, 'https://via.placeholder.com/200?text=Tech14', 'Smart Home', 'Tech', 'smart,cleaning'),
('August Smart Lock', 'Slim deurvergrendeling', 195, 'https://via.placeholder.com/200?text=Tech15', 'Smart Home', 'Tech', 'smart,security'),
('Ring Smart Doorbell', 'Video deurbel camera', 120, 'https://via.placeholder.com/200?text=Tech16', 'Smart Home', 'Tech', 'smart,security'),
('Logitech Circle Webcam', 'Home security camera', 75, 'https://via.placeholder.com/200?text=Tech17', 'Smart Home', 'Tech', 'smart,camera'),
('Wyze Cam V3', 'Budget outdoor camera', 32, 'https://via.placeholder.com/200?text=Tech18', 'Smart Home', 'Tech', 'smart,camera'),
('Apple iPhone 15 Pro', 'Latest iPhone premium', 999, 'https://via.placeholder.com/200?text=Tech19', 'Tech', 'Tech', 'tech,mobile'),
('Samsung Galaxy S24 Ultra', 'Samsung flagship phone', 1049, 'https://via.placeholder.com/200?text=Tech20', 'Tech', 'Tech', 'tech,mobile'),
('iPad Pro 12.9 inch', 'Apple tablet premium', 1099, 'https://via.placeholder.com/200?text=Tech21', 'Tech', 'Tech', 'tech,tablet'),
('Samsung Galaxy Tab S9', 'Android tablet flagship', 699, 'https://via.placeholder.com/200?text=Tech22', 'Tech', 'Tech', 'tech,tablet'),
('Apple MacBook Pro 16', 'MacBook laptop premium', 2299, 'https://via.placeholder.com/200?text=Tech23', 'Tech', 'Tech', 'tech,laptop'),
('Dell XPS 15 Laptop', 'Premium Windows laptop', 1699, 'https://via.placeholder.com/200?text=Tech24', 'Tech', 'Tech', 'tech,laptop'),
('Apple Watch Ultra', 'Premium smartwatch', 399, 'https://via.placeholder.com/200?text=Tech25', 'Tech', 'Tech', 'tech,watch'),
('Samsung Galaxy Watch 6', 'Android smartwatch', 299, 'https://via.placeholder.com/200?text=Tech26', 'Tech', 'Tech', 'tech,watch'),
('Fitbit Charge 6', 'Fitness tracker band', 179, 'https://via.placeholder.com/200?text=Tech27', 'Tech', 'Tech', 'tech,fitness'),
('Garmin Epix Gen 2', 'Premium sports watch', 449, 'https://via.placeholder.com/200?text=Tech28', 'Tech', 'Tech', 'tech,sports'),
('Anker PowerBank 65W', 'Snelle powerbank', 45, 'https://via.placeholder.com/200?text=Tech29', 'Tech', 'Tech', 'tech,charging'),
('Mophie Wireless Charger', 'Draadloos oplaad pad', 35, 'https://via.placeholder.com/200?text=Tech30', 'Tech', 'Tech', 'tech,charging'),
('UGREEN USB-C Hub', 'Multiport USB hub', 38, 'https://via.placeholder.com/200?text=Tech31', 'Tech', 'Tech', 'tech,hub'),
('CalDigit Thunderbolt Dock', 'Premium docking station', 299, 'https://via.placeholder.com/200?text=Tech32', 'Tech', 'Tech', 'tech,dock'),
('Samsung 4K Monitor 32', '32 inch 4K display', 450, 'https://via.placeholder.com/200?text=Tech33', 'Tech', 'Tech', 'tech,monitor'),
('LG UltraWide Monitor 38', '38 inch ultrawide display', 1100, 'https://via.placeholder.com/200?text=Tech34', 'Tech', 'Tech', 'tech,monitor'),
('Canon EOS R50 Camera', 'Mirrorless digitale camera', 650, 'https://via.placeholder.com/200?text=Tech35', 'Tech', 'Tech', 'tech,camera'),
('Sony A6700 Camera', 'Premium mirrorless camera', 1300, 'https://via.placeholder.com/200?text=Tech36', 'Tech', 'Tech', 'tech,camera'),
('DJI Mini 3 Pro Drone', 'Portable camera drone', 320, 'https://via.placeholder.com/200?text=Tech37', 'Tech', 'Tech', 'tech,drone'),
('DJI Air 3 Drone', 'Advanced camera drone aerial', 900, 'https://via.placeholder.com/200?text=Tech38', 'Tech', 'Tech', 'tech,drone'),
('GoPro Hero 12 Camera', 'Action camera compact', 380, 'https://via.placeholder.com/200?text=Tech39', 'Tech', 'Tech', 'tech,action'),
('Insta360 X3 Camera', '360 degree camera action', 420, 'https://via.placeholder.com/200?text=Tech40', 'Tech', 'Tech', 'tech,360');

-- ===== KOKEN & BAKKEN - 80 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Luxe Keramische Panneset', 'Set meerdere pan antiaanbak', 95, 'https://via.placeholder.com/200?text=Kitchen1', 'Koken', 'Keuken', 'koken,pannen'),
('Gietijzeren Braadpan', 'Cast iron dutch oven', 120, 'https://via.placeholder.com/200?text=Kitchen2', 'Koken', 'Keuken', 'koken,braden'),
('Professionele Chefmessen Set', 'Set 6 chef messen', 75, 'https://via.placeholder.com/200?text=Kitchen3', 'Koken', 'Keuken', 'koken,messen'),
('Air Fryer XXL Philips', 'Grote airfryer thuis', 130, 'https://via.placeholder.com/200?text=Kitchen4', 'Koken', 'Keuken', 'koken,airfryer'),
('Instant Pot Multi Cooker', 'Elektrische snelkookpan', 95, 'https://via.placeholder.com/200?text=Kitchen5', 'Koken', 'Keuken', 'koken,appliance'),
('Sous Vide Immersion Heater', 'Precisiekookstick', 95, 'https://via.placeholder.com/200?text=Kitchen6', 'Koken', 'Keuken', 'koken,tech'),
('Blender Ninja Professional', 'Professionele blender', 85, 'https://via.placeholder.com/200?text=Kitchen7', 'Koken', 'Keuken', 'koken,mixer'),
('Food Processor KitchenAid', 'Voedselverwerker machine', 120, 'https://via.placeholder.com/200?text=Kitchen8', 'Koken', 'Keuken', 'koken,appliance'),
('Stand Mixer KitchenAid', 'Keukenmixer stand', 285, 'https://via.placeholder.com/200?text=Kitchen9', 'Bakken', 'Keuken', 'bakken,mixer'),
('Espresso Machine DeLonghi', 'Thuiskoffieapparaat cappuccino', 145, 'https://via.placeholder.com/200?text=Kitchen10', 'Koffie', 'Keuken', 'koffie,espresso'),
('Moccamaster Koffiezetapparaat', 'Premium filter koffie', 165, 'https://via.placeholder.com/200?text=Kitchen11', 'Koffie', 'Keuken', 'koffie,brewer'),
('Nespresso Machine', 'Capsule espresso machine', 180, 'https://via.placeholder.com/200?text=Kitchen12', 'Koffie', 'Keuken', 'koffie,capsule'),
('Melkopschuimer Elektronisch', 'Elektrische milk frother', 35, 'https://via.placeholder.com/200?text=Kitchen13', 'Koffie', 'Keuken', 'koffie,accessories'),
('Coffee Grinder Burr', 'Bonen maler grinder', 78, 'https://via.placeholder.com/200?text=Kitchen14', 'Koffie', 'Keuken', 'koffie,maler'),
('Bakmat Premium Silicoon', 'Bakmatten doos 2', 32, 'https://via.placeholder.com/200?text=Kitchen15', 'Bakken', 'Keuken', 'bakken,mat'),
('Oven Thermometer Digital', 'Digitale oventhermometer', 18, 'https://via.placeholder.com/200?text=Kitchen16', 'Bakken', 'Keuken', 'bakken,thermometer'),
('Cake Decorating Set', 'Taart decoratie toolkit', 28, 'https://via.placeholder.com/200?text=Kitchen17', 'Bakken', 'Keuken', 'bakken,decoratie'),
('Piping Bag Set 20-Piece', 'Spuitzakken met nozzles', 18, 'https://via.placeholder.com/200?text=Kitchen18', 'Bakken', 'Keuken', 'bakken,decoratie'),
('Stand Mixer Bowl Upgrade', 'Mixer bowl upgrade', 45, 'https://via.placeholder.com/200?text=Kitchen19', 'Bakken', 'Keuken', 'bakken,accessories'),
('Baking Stone Pizza', 'Pizzasteen keramiek', 32, 'https://via.placeholder.com/200?text=Kitchen20', 'Bakken', 'Keuken', 'bakken,steen'),
('Grill Thermometer Wireless', 'BBQ thermometer draadloos', 38, 'https://via.placeholder.com/200?text=Kitchen21', 'Koken', 'Keuken', 'koken,grill'),
('BBQ Smoker Box', 'Rook generator smoker', 45, 'https://via.placeholder.com/200?text=Kitchen22', 'Koken', 'Keuken', 'koken,smoker'),
('Kettle Water Boiler Electric', 'Elektrische waterkoker', 22, 'https://via.placeholder.com/200?text=Kitchen23', 'Koffie', 'Keuken', 'koffie,kettle'),
('Tea Infuser Set', 'thee infuser toolkit', 28, 'https://via.placeholder.com/200?text=Kitchen24', 'Koffie', 'Keuken', 'thee,infuser'),
('Kitchen Scale Digital Precision', 'Digitale keukenschaal', 35, 'https://via.placeholder.com/200?text=Kitchen25', 'Bakken', 'Keuken', 'bakken,scale'),
('Meat Thermometer Bluetooth', 'BBQ vlees thermometer', 32, 'https://via.placeholder.com/200?text=Kitchen26', 'Koken', 'Keuken', 'koken,thermometer'),
('Measuring Cups Set Stainless', 'Maatbekertjes set', 12, 'https://via.placeholder.com/200?text=Kitchen27', 'Bakken', 'Keuken', 'bakken,meten'),
('Wooden Spoon Set', 'Houten lepels set', 15, 'https://via.placeholder.com/200?text=Kitchen28', 'Koken', 'Keuken', 'koken,bestek'),
('Cutting Board Set Wood', 'Snijplankjes set', 28, 'https://via.placeholder.com/200?text=Kitchen29', 'Koken', 'Keuken', 'koken,board'),
('Mixed Knife Block', 'Messenblok compleet', 55, 'https://via.placeholder.com/200?text=Kitchen30', 'Koken', 'Keuken', 'koken,messen');

-- ===== MUZIEK - 80 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Fender Stratocaster Gitaar', 'Klassieke elektrische gitaar', 520, 'https://via.placeholder.com/200?text=Music1', 'Gitaar', 'Muziek', 'gitaar,elektrisch'),
('Gibson Les Paul Gitaar', 'Premium elektrische gitaar', 850, 'https://via.placeholder.com/200?text=Music2', 'Gitaar', 'Muziek', 'gitaar,premium'),
('Squier Acoustic Gitaar', 'Beginners akoestische gitaar', 120, 'https://via.placeholder.com/200?text=Music3', 'Gitaar', 'Muziek', 'gitaar,akoustisch'),
('Yamaha Akoestische Gitaar', 'Middenklasse akoestische', 178, 'https://via.placeholder.com/200?text=Music4', 'Gitaar', 'Muziek', 'gitaar,akoustisch'),
('Ibanez Elektrische Gitaar', 'Pro-level gitaar', 380, 'https://via.placeholder.com/200?text=Music5', 'Gitaar', 'Muziek', 'gitaar,elektrisch'),
('PRS Custom Gitaar', 'Premium handgemaakte gitaar', 1200, 'https://via.placeholder.com/200?text=Music6', 'Gitaar', 'Muziek', 'gitaar,custom'),
('Electric Guitar Amplifier', 'Gitaar versterker amp', 95, 'https://via.placeholder.com/200?text=Music7', 'Gitaar', 'Muziek', 'gitaar,amp'),
('Bass Guitar Fender', 'Elektrische basgitaar', 280, 'https://via.placeholder.com/200?text=Music8', 'Basgitaar', 'Muziek', 'basgitaar,elektrisch'),
('Yamaha TRBX Bass', 'Middenklasse basgitaar', 185, 'https://via.placeholder.com/200?text=Music9', 'Basgitaar', 'Muziek', 'basgitaar,elektrisch'),
('Bass Amplifier 200W', 'Basgitaar versterker', 150, 'https://via.placeholder.com/200?text=Music10', 'Basgitaar', 'Muziek', 'basgitaar,amp'),
('Ukulele Soprano Beginner', 'Beginners ukelele', 45, 'https://via.placeholder.com/200?text=Music11', 'Ukelele', 'Muziek', 'ukelele,klein'),
('Ukulele Tenor Premium', 'Premium 4-snaar ukelele', 95, 'https://via.placeholder.com/200?text=Music12', 'Ukelele', 'Muziek', 'ukelele,tenor'),
('Casio Keyboard 61 Keys', 'Digitale piano keyboard', 85, 'https://via.placeholder.com/200?text=Music13', 'Toetsen', 'Muziek', 'piano,keyboard'),
('Yamaha Piaggero Digital Piano', 'Portable digitale piano', 165, 'https://via.placeholder.com/200?text=Music14', 'Toetsen', 'Muziek', 'piano,digital'),
('Roland FP-30X Portable Piano', 'Professional stage piano', 420, 'https://via.placeholder.com/200?text=Music15', 'Toetsen', 'Muziek', 'piano,stage'),
('Acoustic Piano Starter', 'Akoestische piano thuis', 3500, 'https://via.placeholder.com/200?text=Music16', 'Toetsen', 'Muziek', 'piano,akoustisch'),
('Grand Piano Premium', 'Vleugel piano klassiek', 8000, 'https://via.placeholder.com/200?text=Music17', 'Toetsen', 'Muziek', 'piano,grand'),
('Violin 4/4 Full Size', 'Volwaardige viool', 180, 'https://via.placeholder.com/200?text=Music18', 'Snaren', 'Muziek', 'viool,full'),
('Cello Half Size', 'Halve cello voor beginners', 195, 'https://via.placeholder.com/200?text=Music19', 'Snaren', 'Muziek', 'cello,kleine'),
('Acoustic Drum Kit Complete', 'Complete drumstel', 250, 'https://via.placeholder.com/200?text=Music20', 'Drums', 'Muziek', 'drums,akoustisch'),
('Electronic Drum Kit Pro', 'Digitaal electronic drums', 380, 'https://via.placeholder.com/200?text=Music21', 'Drums', 'Muziek', 'drums,elektronisch'),
('Drum Throne Pedaal Set', 'Drumstoeltje met pedaal', 65, 'https://via.placeholder.com/200?text=Music22', 'Drums', 'Muziek', 'drums,accessories'),
('Trumpet Yamaha YTR', 'Beginners trompet', 145, 'https://via.placeholder.com/200?text=Music23', 'Blaas', 'Muziek', 'trompet,begin'),
('Saxophone Alto Beginner', 'Beginners altsaxofoon', 185, 'https://via.placeholder.com/200?text=Music24', 'Blaas', 'Muziek', 'sax,alto'),
('Saxophone Tenor Professional', 'Professionele tenorsaxofoon', 520, 'https://via.placeholder.com/200?text=Music25', 'Blaas', 'Muziek', 'sax,tenor'),
('Clarinet Wood Beginner', 'Houten klarinet', 125, 'https://via.placeholder.com/200?text=Music26', 'Blaas', 'Muziek', 'klarinet,hout'),
('Flute Silver Nickel', 'Zilveren fluit', 95, 'https://via.placeholder.com/200?text=Music27', 'Blaas', 'Muziek', 'fluit,zilver'),
('Microphone Condenser Studio', 'Studiomicrofoon condensator', 75, 'https://via.placeholder.com/200?text=Music28', 'Opname', 'Muziek', 'microfoon,studio'),
('Dynamic Microphone Shure', 'Professionele dynamische mic', 95, 'https://via.placeholder.com/200?text=Music29', 'Opname', 'Muziek', 'microfoon,live'),
('Microphone Stand Boom', 'Microfoonstandaard boom', 28, 'https://via.placeholder.com/200?text=Music30', 'Opname', 'Muziek', 'microfoon,stand'),
('XLR Cable Professional', 'Audio microfoon kabel', 15, 'https://via.placeholder.com/200?text=Music31', 'Opname', 'Muziek', 'audio,kabel'),
('Audio Interface Scarlett', 'Audio interface USB', 95, 'https://via.placeholder.com/200?text=Music32', 'Opname', 'Muziek', 'opnamedilà,interface'),
('Mixing Console Behringer', 'Geluidsmengtafel mixer', 110, 'https://via.placeholder.com/200?text=Music33', 'Opname', 'Muziek', 'mixer,behringer'),
('Studio Monitor Speakers Pair', 'Studio speakers paar', 165, 'https://via.placeholder.com/200?text=Music34', 'Opname', 'Muziek', 'speakers,studio'),
('Vinyl Turntable Pro', 'Platenspeler draaitafel', 185, 'https://via.placeholder.com/200?text=Music35', 'Vinyl', 'Muziek', 'vinyl,turntable'),
('Vinyl Records Classic Hits', 'Klassieke vinyl platen', 25, 'https://via.placeholder.com/200?text=Music36', 'Vinyl', 'Muziek', 'vinyl,records'),
('Headphone Amplifier DAC', 'Koptelefoon versterker DAC', 120, 'https://via.placeholder.com/200?text=Music37', 'Audio', 'Muziek', 'audio,amp'),
('Music Metronome Digital', 'Digitale metronoom', 32, 'https://via.placeholder.com/200?text=Music38', 'Accessoires', 'Muziek', 'muziek,metronoom');

-- ===== MEDIA & ENTERTAINMENT - 70 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('4K Projector Home Cinema', 'Home theater projector 4K', 850, 'https://via.placeholder.com/200?text=Media1', 'Home Cinema', 'Media', 'cinema,projector'),
('OLED TV 65 inch LG', 'Premium OLED televisie', 1200, 'https://via.placeholder.com/200?text=Media2', 'TV', 'Media', 'tv,oled'),
('4K LED TV 55 inch', 'Smart TV 4K display', 450, 'https://via.placeholder.com/200?text=Media3', 'TV', 'Media', 'tv,led'),
('TV Wall Mount Bracket', 'Beugel voor TV', 35, 'https://via.placeholder.com/200?text=Media4', 'TV', 'Media', 'tv,mount'),
('DVD Player Blu-Ray', 'Disc speler bluray', 85, 'https://via.placeholder.com/200?text=Media5', 'Media Players', 'Media', 'dvd,bluray'),
('Netflix Subscription 1 Year', 'Netflix 12 maanden', 140, 'https://via.placeholder.com/200?text=Media6', 'Streaming', 'Media', 'streaming,netflix'),
('Disney+ Subscription 1 Jaar', 'Disney plus 12 maanden', 100, 'https://via.placeholder.com/200?text=Media7', 'Streaming', 'Media', 'streaming,disney'),
('Amazon Prime Video 1 Jaar', 'Prime video 12 maanden', 60, 'https://via.placeholder.com/200?text=Media8', 'Streaming', 'Media', 'streaming,prime'),
('Apple TV+ Subscription 1 jaar', 'Apple TV+ abonnement', 80, 'https://via.placeholder.com/200?text=Media9', 'Streaming', 'Media', 'streaming,apple'),
('HBO Max Subscription Pro', 'HBO Max premium 12 mnd', 150, 'https://via.placeholder.com/200?text=Media10', 'Streaming', 'Media', 'streaming,hbo'),
('Kaleido TV Streaming Device', 'Android TV streaming box', 45, 'https://via.placeholder.com/200?text=Media11', 'Streaming', 'Media', 'streaming,box'),
('Apple TV 4K Media Box', 'Apple media streaming box', 199, 'https://via.placeholder.com/200?text=Media12', 'Streaming', 'Media', 'streaming,apple'),
('Roku Streaming Stick Plus', 'Roku streaming dongle', 45, 'https://via.placeholder.com/200?text=Media13', 'Streaming', 'Media', 'streaming,roku'),
('Movie Collection Boxset', 'Film serie bluray', 35, 'https://via.placeholder.com/200?text=Media14', 'Physical Media', 'Media', 'film,boxset'),
('4K Movie Bundle Pack', 'Bundel 4K films', 48, 'https://via.placeholder.com/200?text=Media15', 'Physical Media', 'Media', 'film,4k'),
('Gaming Monitor 144Hz', 'Gamer monitor curved', 280, 'https://via.placeholder.com/200?text=Media16', 'Gaming', 'Media', 'gaming,monitor'),
('Podcast Mic Setup', 'Podcast microfoon kit', 120, 'https://via.placeholder.com/200?text=Media17', 'Audio', 'Media', 'podcast,mic'),
('Video Lighting kit', 'YouTube studio lights set', 75, 'https://via.placeholder.com/200?text=Media18', 'Production', 'Media', 'video,lights'),
('Tripod for Phone/Camera', 'Video tripod professioneel', 45, 'https://via.placeholder.com/200?text=Media19', 'Production', 'Media', 'video,tripod'),
('GoPro Mounting Kit', 'Action camera mount set', 32, 'https://via.placeholder.com/200?text=Media20', 'Production', 'Media', 'video,mount');

-- ===== FOTOGRAFIE - 80 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Nikon D850 DSLR Camera', 'Professional DSLR fototoestel', 1250, 'https://via.placeholder.com/200?text=Photo1', 'Fotografie', 'Fotografie', 'camera,dslr'),
('Canon EOS R5 Mirrorless', 'Premium mirrorless fotocamera', 1380, 'https://via.placeholder.com/200?text=Photo2', 'Fotografie', 'Fotografie', 'camera,mirrorless'),
('Sony a7 Mark IV', 'Full frame mirrorless camera', 1250, 'https://via.placeholder.com/200?text=Photo3', 'Fotografie', 'Fotografie', 'camera,sony'),
('Canon EF 24-70mm Lens', 'Standaard zoom lens', 385, 'https://via.placeholder.com/200?text=Photo4', 'Fotografie', 'Fotografie', 'lens,zoom'),
('Nikon AF-S Nikkor 35mm', 'Prime lens 35mm', 220, 'https://via.placeholder.com/200?text=Photo5', 'Fotografie', 'Fotografie', 'lens,prime'),
('Sony 85mm f/1.4 Lens', 'Portrait prime lens', 1198, 'https://via.placeholder.com/200?text=Photo6', 'Fotografie', 'Fotografie', 'lens,portrait'),
('Nikon 70-200mm Telephoto', 'Tele zoom lens', 280, 'https://via.placeholder.com/200?text=Photo7', 'Fotografie', 'Fotografie', 'lens,telephoto'),
('Wide Angle Lens 14-24mm', 'Ultra wide zoom', 320, 'https://via.placeholder.com/200?text=Photo8', 'Fotografie', 'Fotografie', 'lens,ultrawide'),
('Macro Lens 105mm', 'Macro fotogrfie lens', 195, 'https://via.placeholder.com/200?text=Photo9', 'Fotografie', 'Fotografie', 'lens,macro'),
('Fisheye Lens 8mm', 'Extreme wide angle', 280, 'https://via.placeholder.com/200?text=Photo10', 'Fotografie', 'Fotografie', 'lens,fisheye'),
('Tripod Carbon Fiber Pro', 'Anti-shake carbon tripod', 180, 'https://via.placeholder.com/200?text=Photo11', 'Fotografie', 'Fotografie', 'tripod,carbon'),
('Motorized Gimbal 3-Axis', 'Video stabilizer gimbal', 140, 'https://via.placeholder.com/200?text=Photo12', 'Fotografie', 'Fotografie', 'gimbal,video'),
('Studio Light Kit 3-Piece', 'Fotografie studio verlichting', 95, 'https://via.placeholder.com/200?text=Photo13', 'Fotografie', 'Fotografie', 'lighting,studio'),
('Reflector Photography Set', 'Light reflector set 5in1', 32, 'https://via.placeholder.com/200?text=Photo14', 'Fotografie', 'Fotografie', 'reflector,light'),
('Photography Backdrop Stand', 'Achtergrondsysteem stand', 65, 'https://via.placeholder.com/200?text=Photo15', 'Fotografie', 'Fotografie', 'backdrop,stand'),
('Softbox Photography 1.2m', 'Diffuser softbox set', 85, 'https://via.placeholder.com/200?text=Photo16', 'Fotografie', 'Fotografie', 'softbox,diffuser'),
('Camera Bag Weather Proof', 'Beveiligde camera tas', 75, 'https://via.placeholder.com/200?text=Photo17', 'Fotografie', 'Fotografie', 'bags,protection'),
('Lens Cleaning Kit Premium', 'Lenzen schoonmaak set', 18, 'https://via.placeholder.com/200?text=Photo18', 'Fotografie', 'Fotografie', 'cleaning,preservatie'),
('ND Filter Set Gradient', 'Neutrale densiteit filters', 35, 'https://via.placeholder.com/200?text=Photo19', 'Fotografie', 'Fotografie', 'filter,nd'),
('UV Protection Filter', 'Protective UV filter set', 22, 'https://via.placeholder.com/200?text=Photo20', 'Fotografie', 'Fotografie', 'filter,uv'),
('Circular Polarizer Filter', 'CPL filter 52-77mm', 28, 'https://via.placeholder.com/200?text=Photo21', 'Fotografie', 'Fotografie', 'filter,polarizer'),
('Lens Hood Shade Adapter', 'Lens shade hood set', 18, 'https://via.placeholder.com/200?text=Photo22', 'Fotografie', 'Fotografie', 'lens,hood'),
('Camera Strap Comfortable', 'Camera draagriem sling', 28, 'https://via.placeholder.com/200?text=Photo23', 'Fotografie', 'Fotografie', 'strap,comfort'),
('Memory Card SSD 1TB', 'High-speed SD card storage', 85, 'https://via.placeholder.com/200?text=Photo24', 'Fotografie', 'Fotografie', 'storage,card'),
('Portable Hard Drive 4TB', 'Externe backup drive', 120, 'https://via.placeholder.com/200?text=Photo25', 'Fotografie', 'Fotografie', 'storage,backup');

-- ===== KUNST & TEKENEN - 60 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Professional Marker Set 120', 'Professionele markers 120 kleuren', 85, 'https://via.placeholder.com/200?text=Art1', 'Tekenen', 'Kunst', 'markers,professional'),
('Watercolor Paint Professional', 'Professionele aquarel set', 75, 'https://via.placeholder.com/200?text=Art2', 'Schilderen', 'Kunst', 'watercolor,set'),
('Acrylic Paint Art Set', 'Acrylverf kunst set 60 kleuren', 55, 'https://via.placeholder.com/200?text=Art3', 'Schilderen', 'Kunst', 'acrylic,colors'),
('Oil Paint Professional', 'Olieverf professioneel set', 95, 'https://via.placeholder.com/200?text=Art4', 'Schilderen', 'Kunst', 'oil,paint'),
('Professional Sketching Pencil', 'Schetspennen set 24-piece', 32, 'https://via.placeholder.com/200?text=Art5', 'Tekenen', 'Kunst', 'pencils,sketch'),
('Colored Pencil Soft Core', 'Gekleurde potloden soft 72', 42, 'https://via.placeholder.com/200?text=Art6', 'Tekenen', 'Kunst', 'pencils,colored'),
('Charcoal Drawing Set', 'Houtskoolstiften arte set', 28, 'https://via.placeholder.com/200?text=Art7', 'Tekenen', 'Kunst', 'charcoal,drawing'),
('Graphite Pencil Set Hard', 'Grafietpotloden harde set', 18, 'https://via.placeholder.com/200?text=Art8', 'Tekenen', 'Kunst', 'graphite,pencils'),
('Canvas Pad Large', 'Gran canvaskussen art', 32, 'https://via.placeholder.com/200?text=Art9', 'Schilderen', 'Kunst', 'canvas,pad'),
('Canvas Board Set 10', 'Canvas Board set 10-piece', 28, 'https://via.placeholder.com/200?text=Art10', 'Schilderen', 'Kunst', 'canvas,board'),
('Wooden Canvas Stretcher', 'Canvas frame stretcher kit', 45, 'https://via.placeholder.com/200?text=Art11', 'Schilderen', 'Kunst', 'canvas,stretcher'),
('Brush Set Complete', 'Penselenset alles soorten', 35, 'https://via.placeholder.com/200?text=Art12', 'Tekenen', 'Kunst', 'brushes,set'),
('Brush Cleaning Solution', 'Penselen schoonmaa vloeistof', 12, 'https://via.placeholder.com/200?text=Art13', 'Tekenen', 'Kunst', 'brushes,cleaner'),
('Sketchbook Large Premium', 'Schetsboek A3 premium', 22, 'https://via.placeholder.com/200?text=Art14', 'Tekenen', 'Kunst', 'sketchbook,large'),
('Drawing Tablet Wacom', 'Digitale tekenpad Wacom', 85, 'https://via.placeholder.com/200?text=Art15', 'Digitaal', 'Kunst', 'digital,tablet'),
('Pen Display Graphics Tablet', 'Graphic pen display monitor', 280, 'https://via.placeholder.com/200?text=Art16', 'Digitaal', 'Kunst', 'graphic,display'),
('Art Easel Tripod Adjustable', 'Schildersezel standaard', 45, 'https://via.placeholder.com/200?text=Art17', 'Schilderen', 'Kunst', 'easel,adjustable'),
('Studio Easel Professional', 'Professionele studio ezel', 120, 'https://via.placeholder.com/200?text=Art18', 'Schilderen', 'Kunst', 'easel,studio'),
('Palette Mixing Colors', 'Palet mengkleuren set', 15, 'https://via.placeholder.com/200?text=Art19', 'Schilderen', 'Kunst', 'palette,mixing'),
('Palette Knife Set Metal', 'Palet messen set metaal', 18, 'https://via.placeholder.com/200?text=Art20', 'Schilderen', 'Kunst', 'knife,palette');

-- ===== SPELLEN & PUZZELS - 50 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Chess Set Premium Wood', 'Premium houten schaakset', 65, 'https://via.placeholder.com/200?text=Games1', 'Bordspelen', 'Spellen', 'chess,wood'),
('Chess Clock Digital', 'Digitale schaaklok timer', 35, 'https://via.placeholder.com/200?text=Games2', 'Bordspelen', 'Spellen', 'chess,clock'),
('Monopoly Board Game', 'Klassiek monopoly spel', 28, 'https://via.placeholder.com/200?text=Games3', 'Bordspelen', 'Spellen', 'board,classic'),
('Catan Card Game', 'Catan bordspel kaarten', 42, 'https://via.placeholder.com/200?text=Games4', 'Bordspelen', 'Spellen', 'board,strategy'),
('Carcassonne Tile Game', 'Carcassonne bordspel', 32, 'https://via.placeholder.com/200?text=Games5', 'Bordspelen', 'Spellen', 'board,tiles'),
('Ticket to Ride Game', 'Train route board game', 38, 'https://via.placeholder.com/200?text=Games6', 'Bordspelen', 'Spellen', 'board,trains'),
('Pandemic Board Game', 'Pandemic samenwerk spel', 35, 'https://via.placeholder.com/200?text=Games7', 'Bordspelen', 'Spellen', 'board,cooperative'),
('Scrabble Deluxe Edition', 'Deluxe woordenspel', 32, 'https://via.placeholder.com/200?text=Games8', 'Bordspelen', 'Spellen', 'word,scrabble'),
('Jigsaw Puzzle 1000 Piece', '1000 stukjes puzzel kunstwerk', 18, 'https://via.placeholder.com/200?text=Games9', 'Puzzels', 'Spellen', 'puzzle,1000'),
('3D Puzzle Building Kit', '3D bouw puzzel model', 28, 'https://via.placeholder.com/200?text=Games10', 'Puzzels', 'Spellen', 'puzzle,3d'),
('Rubik Cube Speed', 'Rubik kubus speedcube', 15, 'https://via.placeholder.com/200?text=Games11', 'Puzzels', 'Spellen', 'cube,speed'),
('Magic Cube 3x3 Professional', 'Professionele magic cube', 18, 'https://via.placeholder.com/200?text=Games12', 'Puzzels', 'Spellen', 'cube,magic'),
('Playing Cards Premium', 'Premium speelkaarten set', 12, 'https://via.placeholder.com/200?text=Games13', 'Spelelsetdagen', 'Spellen', 'cards,playing'),
('Uno Card Game', 'Uno kaartspel familie', 10, 'https://via.placeholder.com/200?text=Games14', 'Kaartspelen', 'Spellen', 'cards,uno'),
('Poker Chip Set 500', '500-delige pokerchips set', 35, 'https://via.placeholder.com/200?text=Games15', 'Spelen', 'Spellen', 'poker,chips'),
('Dominoes Game Double Six', 'Klassieke dominoes', 15, 'https://via.placeholder.com/200?text=Games16', 'Bordspelen', 'Spellen', 'dominoes,classic');

-- ===== FASHION & ACCESSOIRES - 70 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Designer Zonnebril Premium', 'Merk zonnebril UV bescherming', 85, 'https://via.placeholder.com/200?text=Fashion1', 'Accessoires', 'Fashion', 'sunglasses,designer'),
('Leren Riem Premium', 'Italiaans leer riem', 45, 'https://via.placeholder.com/200?text=Fashion2', 'Accessoires', 'Fashion', 'belt,leather'),
('Duur Horloge Analog', 'Klassiek design horloge', 185, 'https://via.placeholder.com/200?text=Fashion3', 'Horloges', 'Fashion', 'watch,analog'),
('Smartwatch Sportuiteruste', 'Sport smartwatch fitness', 95, 'https://via.placeholder.com/200?text=Fashion4', 'Horloges', 'Fashion', 'watch,smart'),
('Elegante Schoenen Leer', 'Formele leren schoenen', 125, 'https://via.placeholder.com/200?text=Fashion5', 'Schoenen', 'Fashion', 'shoes,formal'),
('Sneakers Premium Merk', 'Designer sportschoenen', 95, 'https://via.placeholder.com/200?text=Fashion6', 'Schoenen', 'Fashion', 'shoes,sneakers'),
('Winterjas Waterdicht', 'Parka waterdichte jas', 165, 'https://via.placeholder.com/200?text=Fashion7', 'Kleding', 'Fashion', 'coat,winter'),
('Blazer Business Elegant', 'Kantoor blazer pak', 145, 'https://via.placeholder.com/200?text=Fashion8', 'Kleding', 'Fashion', 'blazer,business'),
('Denim Jeans Premium', 'Designerjeans casual', 85, 'https://via.placeholder.com/200?text=Fashion9', 'Kleding', 'Fashion', 'jeans,premium'),
('T-shirt Merk Logo', 'Designer branded shirt', 35, 'https://via.placeholder.com/200?text=Fashion10', 'Kleding', 'Fashion', 'shirt,brand'),
('Leren Handtas', 'Designer leder tas', 155, 'https://via.placeholder.com/200?text=Fashion11', 'Tassen', 'Fashion', 'bag,leather'),
('Rugzak Backpack School', 'Schoolrugzak ergonomisch', 65, 'https://via.placeholder.com/200?text=Fashion12', 'Tassen', 'Fashion', 'backpack,school'),
('Sjaal Luxe Katoen', 'Comfort sjaal warm', 32, 'https://via.placeholder.com/200?text=Fashion13', 'Accessoires', 'Fashion', 'scarf,cotton'),
('Handschoenen Winter', 'Warme winterhandschoenen', 25, 'https://via.placeholder.com/200?text=Fashion14', 'Accessoires', 'Fashion', 'gloves,winter'),
('Hoed Fedora Stijl', 'Klassieke hoed elegant', 45, 'https://via.placeholder.com/200?text=Fashion15', 'Accessoires', 'Fashion', 'hat,fedora'),
('Kapmuts Beanie', 'Winter beanie gebreide muts', 15, 'https://via.placeholder.com/200?text=Fashion16', 'Accessoires', 'Fashion', 'beanie,winter');

-- ===== BEAUTY & VERZORGING - 80 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Dyson Supersonic Föhn', 'Premium haardroger tech', 349, 'https://via.placeholder.com/200?text=Beauty1', 'Haar', 'Beauty', 'hair,dryer'),
('GHD Straightener Professional', 'Professionele haarplaat', 195, 'https://via.placeholder.com/200?text=Beauty2', 'Haar', 'Beauty', 'hair,straightener'),
('Dyson Curling Iron', 'Krul machine tech', 286, 'https://via.placeholder.com/200?text=Beauty3', 'Haar', 'Beauty', 'hair,curling'),
('Revlon Hair Dryer Brush', 'Föhn borstelmachine combo', 52, 'https://via.placeholder.com/200?text=Beauty4', 'Haar', 'Beauty', 'hair,brush'),
('Oral B Electric Toothbrush', 'Electrische tandenborstel', 42, 'https://via.placeholder.com/200?text=Beauty5', 'Tandenpoets', 'Beauty', 'teeth,brush'),
('Philips Sonicare Pro', 'Premium tandenborstel sonic', 85, 'https://via.placeholder.com/200?text=Beauty6', 'Tandenpoets', 'Beauty', 'teeth,sonic'),
('Water Flosser Irrigator', 'Tandengat waterpot', 38, 'https://via.placeholder.com/200?text=Beauty7', 'Tandenpoets', 'Beauty', 'teeth,flosser'),
('Silk Pillowcase Skin', 'Anti-rimpel zijden kussen', 28, 'https://via.placeholder.com/200?text=Beauty8', 'Huid', 'Beauty', 'skin,pillow'),
('Face Roller Jade Gua Sha', 'Gezichtsroller massage', 18, 'https://via.placeholder.com/200?text=Beauty9', 'Huid', 'Beauty', 'skin,roller'),
('LED Face Mask Therapy', 'Gezichtsmasker licht therapie', 95, 'https://via.placeholder.com/200?text=Beauty10', 'Huid', 'Beauty', 'skin,mask'),
('Electric Face Brush', 'Gezichtsborstel reiniger', 45, 'https://via.placeholder.com/200?text=Beauty11', 'Huid', 'Beauty', 'skin,brush'),
('Skincare Set Night Cream', 'Nachtcrème set', 48, 'https://via.placeholder.com/200?text=Beauty12', 'Huid', 'Beauty', 'skin,cream'),
('Vitamin C Serum Face', 'Vitamine C serum anti-aging', 32, 'https://via.placeholder.com/200?text=Beauty13', 'Huid', 'Beauty', 'skin,serum'),
('Retinol Age Defying', 'Retinol anti-rimpel', 38, 'https://via.placeholder.com/200?text=Beauty14', 'Huid', 'Beauty', 'skin,retinol'),
('Hyaluronic Acid Serum', 'Hyaluronzuur moisturizer', 35, 'https://via.placeholder.com/200?text=Beauty15', 'Huid', 'Beauty', 'skin,hyaluronic'),
('Face Cleanser Gentle', 'Gezicht reiniger mild', 18, 'https://via.placeholder.com/200?text=Beauty16', 'Huid', 'Beauty', 'skin,cleanser'),
('Sunscreen SPF 50 Face', 'Zonnebrand gezicht UV', 24, 'https://via.placeholder.com/200?text=Beauty17', 'Huid', 'Beauty', 'skin,sunscreen'),
('Moisturizer Day Cream', 'Dagcrème hydratatie', 32, 'https://via.placeholder.com/200?text=Beauty18', 'Huid', 'Beauty', 'skin,moisturizer'),
('Eye Cream Anti-Aging', 'Oogcrème rimpels', 28, 'https://via.placeholder.com/200?text=Beauty19', 'Huid', 'Beauty', 'skin,eyes'),
('Face Mask Sheet Pack 10', 'Gezichtsmasker papieren set', 15, 'https://via.placeholder.com/200?text=Beauty20', 'Huid', 'Beauty', 'skin,sheet'),
('Exfoliating Scrub Gentle', 'Gezicht scrub zacht', 18, 'https://via.placeholder.com/200?text=Beauty21', 'Huid', 'Beauty', 'skin,exfoliating'),
('Acne Treatment Spot', 'Acne pukkeltje behandeling', 14, 'https://via.placeholder.com/200?text=Beauty22', 'Huid', 'Beauty', 'skin,acne'),
('Makeup Brush Set', 'Make-up penselen set', 28, 'https://via.placeholder.com/200?text=Beauty23', 'Make-up', 'Beauty', 'makeup,brushes'),
('Foundation Liquid Full Size', 'Fond liquid make-up', 32, 'https://via.placeholder.com/200?text=Beauty24', 'Make-up', 'Beauty', 'makeup,foundation'),
('Concealer Full Coverage', 'Concealer camouflage make-up', 18, 'https://via.placeholder.com/200?text=Beauty25', 'Make-up', 'Beauty', 'makeup,concealer'),
('Mascara Waterproof', 'Mascara volumineus waterproof', 18, 'https://via.placeholder.com/200?text=Beauty26', 'Make-up', 'Beauty', 'makeup,mascara'),
('Eyeshadow Palette 24 Shades', 'Oogschaduw palet 24k', 35, 'https://via.placeholder.com/200?text=Beauty27', 'Make-up', 'Beauty', 'makeup,eyeshadow'),
('Lipstick Luxury Matte', 'Lippenstift mat luxe', 25, 'https://via.placeholder.com/200?text=Beauty28', 'Make-up', 'Beauty', 'makeup,lipstick'),
('Blush Powder Glow', 'Wangenroze poeder', 18, 'https://via.placeholder.com/200?text=Beauty29', 'Make-up', 'Beauty', 'makeup,blush'),
('Highlighter Strobing', 'Highlight make-up glans', 16, 'https://via.placeholder.com/200?text=Beauty30', 'Make-up', 'Beauty', 'makeup,highlighter');

-- ===== HOME & WONEN - 70 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Luxe Hoeslaken 200TC', 'Premium katoen hoeslaken', 35, 'https://via.placeholder.com/200?text=Home1', 'Bed', 'Home', 'bedding,sheets'),
('Duvet Cover Set Luxe', 'Dekbedovertrek set 100% katoen', 42, 'https://via.placeholder.com/200?text=Home2', 'Bed', 'Home', 'bedding,duvet'),
('Pillow Cases Premium', 'Kussenslopen zijde set', 28, 'https://via.placeholder.com/200?text=Home3', 'Bed', 'Home', 'bedding,pillows'),
('Weighted Blanket Comfort', 'Verzwaarde deken anti-angst', 125, 'https://via.placeholder.com/200?text=Home4', 'Bed', 'Home', 'bedding,weighted'),
('Memory Foam Pillow', 'Memory foam kussen ergonomisch', 45, 'https://via.placeholder.com/200?text=Home5', 'Bed', 'Home', 'bedding,pillow'),
('Down Comforter Goose', 'Ganzendonsdeken winter', 85, 'https://via.placeholder.com/200?text=Home6', 'Bed', 'Home', 'bedding,comforter'),
('Turkish Cotton Towel Set', 'Badhanddoeken set luxe katoen', 32, 'https://via.placeholder.com/200?text=Home7', 'Bad', 'Home', 'towels,cotton'),
('Spa Towel Robe', 'Badjassauna spa gewaad', 52, 'https://via.placeholder.com/200?text=Home8', 'Bad', 'Home', 'robe,spa'),
('Shower Caddy Organizer', 'Douche opbergmand', 22, 'https://via.placeholder.com/200?text=Home9', 'Bad', 'Home', 'bathroom,organizer'),
('Luxury Bath Mat', 'Badmat premium zacht', 28, 'https://via.placeholder.com/200?text=Home10', 'Bad', 'Home', 'bathroom,mat'),
('Rainfall Showerhead', 'Douchekop regen effect', 35, 'https://via.placeholder.com/200?text=Home11', 'Bad', 'Home', 'shower,rainfall'),
('LED Bath Lighting', 'Badkamer verlichting LED', 42, 'https://via.placeholder.com/200?text=Home12', 'Bad', 'Home', 'bathroom,lights'),
('Vanity Mirror LED', 'Spiegeltje led verlichting', 38, 'https://via.placeholder.com/200?text=Home13', 'Bad', 'Home', 'bathroom,mirror'),
('Soap Dispensers Luxury', 'Zeeppomp zeephouder', 18, 'https://via.placeholder.com/200?text=Home14', 'Bad', 'Home', 'bathroom,dispenser'),
('Candle Scented Luxury', 'Geurkaarsset luxe', 32, 'https://via.placeholder.com/200?text=Home15', 'Decoratie', 'Home', 'candles,scented'),
('Essential Oil Diffuser', 'Diffuser aroma etherische oliën', 45, 'https://via.placeholder.com/200?text=Home16', 'Decoratie', 'Home', 'diffuser,oils'),
('Plant Pot Modern', 'Bloempot modern design', 25, 'https://via.placeholder.com/200?text=Home17', 'Decoratie', 'Home', 'plants,pot'),
('Indoor Plant Live', 'Kamerplant groen', 18, 'https://via.placeholder.com/200?text=Home18', 'Decoratie', 'Home', 'plants,living'),
('Picture Frame Set', 'Fotolijst set modern', 28, 'https://via.placeholder.com/200?text=Home19', 'Decoratie', 'Home', 'frames,photo'),
('Wall Decor Mirror Set', 'Spiegels aan muur set', 35, 'https://via.placeholder.com/200?text=Home20', 'Decoratie', 'Home', 'mirrors,wall'),
('Recliner Chair Comfort', 'Uitklapstoel comfort leunstoel', 185, 'https://via.placeholder.com/200?text=Home21', 'Meubels', 'Home', 'furniture,chair'),
('Bean Bag Chair Large', 'Zitzak knuffelstoel gigant', 78, 'https://via.placeholder.com/200?text=Home22', 'Meubels', 'Home', 'furniture,bean'),
('Ottoman Storage Box', 'Ottoman bank opberger', 65, 'https://via.placeholder.com/200?text=Home23', 'Meubels', 'Home', 'furniture,ottoman'),
('Bookshelf Wooden', 'Boekenplank hout modern', 95, 'https://via.placeholder.com/200?text=Home24', 'Meubels', 'Home', 'furniture,shelf'),
('Coffee Table Modern', 'Salontafel design modern', 120, 'https://via.placeholder.com/200?text=Home25', 'Meubels', 'Home', 'furniture,table');

-- ===== ECO & DUURZAAM - 60 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Bamboo Water Bottle', 'Bamboe herbruikbare fles', 18, 'https://via.placeholder.com/200?text=Eco1', 'Eco', 'Eco', 'sustainable,bottle'),
('Organic Cotton Tote Bag', 'Biologisch katoen draagtas', 22, 'https://via.placeholder.com/200?text=Eco2', 'Eco', 'Eco', 'sustainable,bag'),
('Bamboo Lunch Box', 'Bamboe bento broodtrommel', 28, 'https://via.placeholder.com/200?text=Eco3', 'Eco', 'Eco', 'sustainable,lunch'),
('Reusable Straw Set', 'Herbruikbare rietjes staal', 12, 'https://via.placeholder.com/200?text=Eco4', 'Eco', 'Eco', 'sustainable,straws'),
('Bamboo Toothbrush Pack', 'Bamboe tandenborstel set', 15, 'https://via.placeholder.com/200?text=Eco5', 'Eco', 'Eco', 'sustainable,teeth'),
('Eco Friendly Soap', 'Milieuvriendelijke zeep', 8, 'https://via.placeholder.com/200?text=Eco6', 'Eco', 'Eco', 'sustainable,soap'),
('Natural Deodorant', 'Natuurlijk deodorant', 12, 'https://via.placeholder.com/200?text=Eco7', 'Eco', 'Eco', 'sustainable,personal'),
('Organic Cotton Clothing', 'Biologisch katoen shirt', 35, 'https://via.placeholder.com/200?text=Eco8', 'Eco', 'Eco', 'sustainable,clothes'),
('Eco Friendly Yoga Mat', 'Natuurlijke yoga mat', 45, 'https://via.placeholder.com/200?text=Eco9', 'Eco', 'Eco', 'sustainable,yoga'),
('Solar Power Charger', 'Zonne-energie lader', 42, 'https://via.placeholder.com/200?text=Eco10', 'Eco', 'Eco', 'sustainable,energy');

-- ===== HOBBY GEREEDSCHAP & DIY - 80 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Cordless Drill Driver', 'Draadloze boormachine set', 85, 'https://via.placeholder.com/200?text=DIY1', 'DIY', 'DIY', 'tools,drill'),
('Tool Set 126 Piece', 'Gereedschapskist set compleet', 95, 'https://via.placeholder.com/200?text=DIY2', 'DIY', 'DIY', 'tools,set'),
('Power Circular Saw', 'Handcirkelzaag elektro', 75, 'https://via.placeholder.com/200?text=DIY3', 'DIY', 'DIY', 'tools,saw'),
('Rotary Hammer Drill', 'Klopboor beton breek', 125, 'https://via.placeholder.com/200?text=DIY4', 'DIY', 'DIY', 'tools,hammer'),
('Orbital Sander Polisher', 'Schuurmachine orbitaal', 65, 'https://via.placeholder.com/200?text=DIY5', 'DIY', 'DIY', 'tools,sander'),
('Jigsaw Power Saw', 'Decoupeerszaag elektro', 55, 'https://via.placeholder.com/200?text=DIY6', 'DIY', 'DIY', 'tools,jigsaw'),
('Impact Driver Drill', 'Impact hammer driver', 75, 'https://via.placeholder.com/200?text=DIY7', 'DIY', 'DIY', 'tools,impact'),
('Work Bench Table', 'Werkbank tafel DIY', 145, 'https://via.placeholder.com/200?text=DIY8', 'DIY', 'DIY', 'tools,bench'),
('Vise Clamp Clamping', 'Bankschroef spankijzer', 45, 'https://via.placeholder.com/200?text=DIY9', 'DIY', 'DIY', 'tools,vise'),
('Laser Level Measure', 'Laser waterpas meet', 35, 'https://via.placeholder.com/200?text=DIY10', 'DIY', 'DIY', 'tools,level'),
('Measuring Tape Professional', 'Meetlint professioneel lang', 18, 'https://via.placeholder.com/200?text=DIY11', 'DIY', 'DIY', 'tools,measure'),
('Screwdriver Bit Set', 'Schroevendraaier bits set', 22, 'https://via.placeholder.com/200?text=DIY12', 'DIY', 'DIY', 'tools,screwdriver'),
('Wrench Set Adjustable', 'Sleutelset verstelbaar', 32, 'https://via.placeholder.com/200?text=DIY13', 'DIY', 'DIY', 'tools,wrench'),
('Hammer Mallet Pounding', 'Hamer voorslag tools', 12, 'https://via.placeholder.com/200?text=DIY14', 'DIY', 'DIY', 'tools,hammer'),
('Chisel Set Woodwork', 'Beitelset houtbewerking', 28, 'https://via.placeholder.com/200?text=DIY15', 'DIY', 'DIY', 'tools,chisel'),
('Planing Tool Woodwork', 'Schaafmachine hout', 38, 'https://via.placeholder.com/200?text=DIY16', 'DIY', 'DIY', 'tools,plane'),
('Sandpaper Assorted Pack', 'Schuurpapier assortiment', 15, 'https://via.placeholder.com/200?text=DIY17', 'DIY', 'DIY', 'tools,sandpaper'),
('Wood Stain Finish', 'Houtbeits kleuring', 18, 'https://via.placeholder.com/200?text=DIY18', 'DIY', 'DIY', 'tools,stain'),
('Paint Brush Set', 'Kwasten schilderen set', 20, 'https://via.placeholder.com/200?text=DIY19', 'DIY', 'DIY', 'tools,brush'),
('Safety Gear Helmet', 'Veiligheidsbril handschoenen', 28, 'https://via.placeholder.com/200?text=DIY20', 'DIY', 'DIY', 'tools,safety');

-- ===== SPORT EXTRA - 70 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Skateboard Electric Board', 'Elektrisch skateboard motor', 280, 'https://via.placeholder.com/200?text=SportX1', 'Extreme', 'Sport', 'skateboard,electric'),
('Mountain Bike Trail', 'Mountainbike terrein sport', 450, 'https://via.placeholder.com/200?text=SportX2', 'Fietsen', 'Sport', 'bike,mountain'),
('Road Bike Racing', 'Racefiets snelheid sport', 520, 'https://via.placeholder.com/200?text=SportX3', 'Fietsen', 'Sport', 'bike,road'),
('Hybrid Bike Commute', 'Hybridfiets pendelen', 280, 'https://via.placeholder.com/200?text=SportX4', 'Fietsen', 'Sport', 'bike,hybrid'),
('BMX Stunt Bike', 'BMX stunt fiets', 165, 'https://via.placeholder.com/200?text=SportX5', 'Fietsen', 'Sport', 'bike,bmx'),
('Cycling Helmet Safety', 'Fietshelm veiligheid', 45, 'https://via.placeholder.com/200?text=SportX6', 'Fietsen', 'Sport', 'cycling,helmet'),
('Bicycle Lights LED', 'Fietsverlichting LED set', 28, 'https://via.placeholder.com/200?text=SportX7', 'Fietsen', 'Sport', 'cycling,lights'),
('Bike Lock Security', 'Fietsslot beveiliging', 35, 'https://via.placeholder.com/200?text=SportX8', 'Fietsen', 'Sport', 'cycling,lock'),
('Bike Repair Kit Pump', 'Fiets reparatie set pomp', 22, 'https://via.placeholder.com/200?text=SportX9', 'Fietsen', 'Sport', 'cycling,repair'),
('Skateboard Wheels Set', 'Skateboard wielen set', 28, 'https://via.placeholder.com/200?text=SportX10', 'Skateboarden', 'Sport', 'skateboard,wheels'),
('Snowboard Winter Sports', 'Snowboard winter sport', 195, 'https://via.placeholder.com/200?text=SportX11', 'Winter', 'Sport', 'snowboard,winter'),
('Ski Set With Bindings', 'Ski''s ski-binding set winter', 280, 'https://via.placeholder.com/200?text=SportX12', 'Winter', 'Sport', 'skiing,winter'),
('Snowboardboots Winter', 'Snowboard laarzen winter', 95, 'https://via.placeholder.com/200?text=SportX13', 'Winter', 'Sport', 'snowboard,boots'),
('Ski Goggles Winter', 'Ski bril sneeuw winter', 65, 'https://via.placeholder.com/200?text=SportX14', 'Winter', 'Sport', 'skiing,goggles'),
('Winter Coat Insulated', 'Winterjas geïsoleerd warm', 145, 'https://via.placeholder.com/200?text=SportX15', 'Winter', 'Sport', 'winter,coat'),
('Thermal Socks Winter', 'Thermische sokken warm', 18, 'https://via.placeholder.com/200?text=SportX16', 'Winter', 'Sport', 'winter,socks'),
('Hand Warmers Heat', 'Handwarmers warmte herbruikbaar', 12, 'https://via.placeholder.com/200?text=SportX17', 'Winter', 'Sport', 'winter,warmers'),
('Kayak Adventure Boat', 'Kayak recreatie avontuur', 280, 'https://via.placeholder.com/200?text=SportX18', 'Water', 'Sport', 'kayak,water'),
('Paddleboard SUP Board', 'Stand-up paddlefiets bord', 195, 'https://via.placeholder.com/200?text=SportX19', 'Water', 'Sport', 'paddleboard,water'),
('Snorkel Mask Set', 'Snorkel duik set water', 32, 'https://via.placeholder.com/200?text=SportX20', 'Water', 'Sport', 'snorkel,water');

-- ===== REIZEN & AVONTUUR - 60 producten =====
insert into public.products (title, description, price, image_url, hobby_tag, category, tags) values
('Luggage Suitcase Spinner', 'Koffer spinner wielen', 95, 'https://via.placeholder.com/200?text=Travel1', 'Reizen', 'Reizen', 'luggage,suitcase'),
('Backpack Travel Large', 'Reisrugzak groot volume', 65, 'https://via.placeholder.com/200?text=Travel2', 'Reizen', 'Reizen', 'backpack,travel'),
('Travel Pillow Neck', 'Reiskussen nek support', 22, 'https://via.placeholder.com/200?text=Travel3', 'Reizen', 'Reizen', 'travel,pillow'),
('Luggage Tags Set', 'Koffertags labels paket', 12, 'https://via.placeholder.com/200?text=Travel4', 'Reizen', 'Reizen', 'travel,tags'),
('Packing Cubes Organizer', 'Packing organisers set', 18, 'https://via.placeholder.com/200?text=Travel5', 'Reizen', 'Reizen', 'travel,cubes'),
('Travel Jacket Compact', 'Reis blazer compact', 42, 'https://via.placeholder.com/200?text=Travel6', 'Kledij', 'Reizen', 'travel,clothing'),
('Compression Bags Vacuum', 'Vacuüm pakketten compress', 22, 'https://via.placeholder.com/200?text=Travel7', 'Reizen', 'Reizen', 'travel,bags'),
('Portable Wi-Fi Hotspot', 'Reizen Wi-Fi dongle', 65, 'https://via.placeholder.com/200?text=Travel8', 'Tech', 'Reizen', 'travel,wifi'),
('Universal Power Adapter', 'Universele stekkeradapter', 18, 'https://via.placeholder.com/200?text=Travel9', 'Tech', 'Reizen', 'travel,adapter'),
('Camping Tent 4-Person', 'Tent kamperen 4-persoons', 95, 'https://via.placeholder.com/200?text=Travel10', 'Kamperen', 'Reizen', 'camping,tent'),
('Sleeping Bag Warm', 'Slaapzak kamperen warm', 58, 'https://via.placeholder.com/200?text=Travel11', 'Kamperen', 'Reizen', 'camping,sleeping'),
('Camping Backpack 65L', 'Kampeer rugzak groot volume', 75, 'https://via.placeholder.com/200?text=Travel12', 'Kamperen', 'Reizen', 'camping,backpack'),
('Camping Stove Portable', 'Kamp kookstel draagbaar', 35, 'https://via.placeholder.com/200?text=Travel13', 'Kamperen', 'Reizen', 'camping,stove'),
('Camping Cookware Set', 'Kamp keukenset compleet', 45, 'https://via.placeholder.com/200?text=Travel14', 'Kamperen', 'Reizen', 'camping,cookware'),
('Camping Light Lantern', 'Kamp lantaarn verlichting', 25, 'https://via.placeholder.com/200?text=Travel15', 'Kamperen', 'Reizen', 'camping,light'),
('Hiking Boots Trail', 'Wandelschoenen trail', 85, 'https://via.placeholder.com/200?text=Travel16', 'Wandelen', 'Reizen', 'hiking,boots'),
('Walking Poles Trekking', 'Wandelstokken trekking', 32, 'https://via.placeholder.com/200?text=Travel17', 'Wandelen', 'Reizen', 'hiking,poles'),
('Water Proof Backpack', 'Waterdichte rugzak', 45, 'https://via.placeholder.com/200?text=Travel18', 'Wandelen', 'Reizen', 'hiking,backpack'),
('Headlamp Hiking Light', 'Koplampen wandel licht', 28, 'https://via.placeholder.com/200?text=Travel19', 'Wandelen', 'Reizen', 'hiking,light'),
('Emergency Survival Kit', 'Noud survival gereedschap', 35, 'https://via.placeholder.com/200?text=Travel20', 'Survival', 'Reizen', 'survival,kit');

-- Transactie afsluiten
commit;

